language: node_js
node_js: lts/*
cache:
 directories:
   - node_modules
script: 
  - npm test
  - CI=false npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: ${FIREBASE_TOKEN}
